name: Test ML Audit Action

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ML Audit Action
        uses: ./.github/actions/ml-audit
        with:
          repo-url: https://github.com/pytorch/pytorch
